#include "m5auth/vault.hpp"
#include <algorithm>
#include <set>
namespace m5auth::vault { namespace {
constexpr std::uint8_t ALG=1; constexpr std::size_t MF=1024, MS=512;
constexpr std::uint8_t PM[]={'M','5','A','U','T','H','-','V','L','T','-','P','T','1',0};
constexpr std::uint8_t AM[]={'M','5','A','U','T','H','-','V','L','T','-','A','A','D','1',0};
void u16(std::vector<std::uint8_t>& o,std::uint16_t v){o.push_back(v>>8);o.push_back(v&255);} void u64(std::vector<std::uint8_t>& o,std::uint64_t v){for(int s=56;s>=0;s-=8)o.push_back((v>>s)&255);} bool sized(std::vector<std::uint8_t>&o,const std::uint8_t*p,std::size_t n,std::size_t m){if(n>m||n>65535)return false;u16(o,n);o.insert(o.end(),p,p+n);return true;} bool text(std::vector<std::uint8_t>&o,const std::string&s){return sized(o,reinterpret_cast<const std::uint8_t*>(s.data()),s.size(),MF);} struct R{const std::vector<std::uint8_t>&i;std::size_t o=0;bool take(std::size_t n,const std::uint8_t*&p){if(o+n>i.size())return false;p=i.data()+o;o+=n;return true;}bool b(std::uint8_t&v){const std::uint8_t*p;if(!take(1,p))return false;v=*p;return true;}bool w(std::uint16_t&v){const std::uint8_t*p;if(!take(2,p))return false;v=(std::uint16_t(p[0])<<8)|p[1];return true;}bool sz(std::vector<std::uint8_t>&v,std::size_t m){std::uint16_t n;if(!w(n)||n>m)return false;const std::uint8_t*p;if(!take(n,p))return false;v.assign(p,p+n);return true;}bool tx(std::string&s){std::vector<std::uint8_t>b;if(!sz(b,MF))return false;s.assign(reinterpret_cast<const char*>(b.data()),b.size());return true;}}; bool valid(const CredentialRecord&r){return !r.secret.empty()&&r.secret.size()<=MS&&r.digits>=1&&r.digits<=10&&r.period_seconds>=1;}
}
bool encode_plaintext(const VaultPlaintext&v,std::vector<std::uint8_t>&out){if(v.credentials.size()>kMaxCredentials)return false;std::vector<std::uint8_t>t(std::begin(PM),std::end(PM));u16(t,kVaultFormatVersion);u16(t,v.credentials.size());std::set<std::array<std::uint8_t,kCredentialIdBytes>>ids;for(const auto&r:v.credentials){if(!valid(r)||!ids.insert(r.credential_id).second)return false;t.insert(t.end(),r.credential_id.begin(),r.credential_id.end());if(!sized(t,r.secret.data(),r.secret.size(),MS)||!text(t,r.issuer)||!text(t,r.account)||!text(t,r.display_name))return false;t.push_back(ALG);t.push_back(r.digits);u16(t,r.period_seconds);u16(t,r.manual_order);}t.push_back(v.wifi?1:0);if(v.wifi&&(!text(t,v.wifi->ssid)||!text(t,v.wifi->password)))return false;out.swap(t);return true;}
bool decode_plaintext(const std::vector<std::uint8_t>&e,VaultPlaintext&out){R r{e};const std::uint8_t*p;if(!r.take(sizeof(PM),p)||!std::equal(std::begin(PM),std::end(PM),p))return false;std::uint16_t ver,n;if(!r.w(ver)||ver!=kVaultFormatVersion||!r.w(n)||n>kMaxCredentials)return false;VaultPlaintext t;std::set<std::array<std::uint8_t,kCredentialIdBytes>>ids;for(std::uint16_t x=0;x<n;++x){CredentialRecord c;if(!r.take(kCredentialIdBytes,p))return false;std::copy(p,p+kCredentialIdBytes,c.credential_id.begin());if(!ids.insert(c.credential_id).second||!r.sz(c.secret,MS)||c.secret.empty()||!r.tx(c.issuer)||!r.tx(c.account)||!r.tx(c.display_name))return false;std::uint8_t a;if(!r.b(a)||a!=ALG||!r.b(c.digits)||!r.w(c.period_seconds)||!r.w(c.manual_order)||!valid(c))return false;t.credentials.push_back(std::move(c));}std::uint8_t wp;if(!r.b(wp)||wp>1)return false;if(wp){WifiRecord w;if(!r.tx(w.ssid)||!r.tx(w.password))return false;t.wifi=std::move(w);}if(r.o!=e.size())return false;out=std::move(t);return true;}
bool build_vault_aad(const std::array<std::uint8_t,kVaultIdBytes>&id,std::uint64_t g,std::vector<std::uint8_t>&out,std::uint16_t f,std::uint16_t s){if(f!=kVaultFormatVersion||s!=kTargetStorageSchemaVersion)return false;std::vector<std::uint8_t>t(std::begin(AM),std::end(AM));u16(t,f);u16(t,s);t.insert(t.end(),id.begin(),id.end());u64(t,g);out.swap(t);return true;}
}  // namespace m5auth::vault
